routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::resource('postingan', 'PostinganController');
Route::resource('komentar', 'KomentarController');

app/Komentar.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Komentar extends Model
{
  protected $table = "komentar";

  protected $fillable = ['isi', 'postingan_id'];

  public function komentator(){
      return $this->belongsTo('App\Postingan', 'postingan_id');
  }
}

app/Postingan.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Postingan extends Model
{
  protected $table = "postingan";

  protected $fillable = ['isi', 'gambar', 'user_id'];

  public function author(){
      return $this->belongsTo('App\User', 'user_id');
  }

  public function postingan(){
      return $this->hasOne('App\Komentar', 'postingan_id');
  }
}

app/User.php
<?php

namespace App;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    public function user(){
        return $this->hasOne('App\Postingan', 'user_id');
    }
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Contracts\Support\Renderable
     */
    public function index()
    {
        return view('home');
    }
}

app/Http/Controllers/KomentarController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use DB;
use App\Komentar;
use App\Postingan;

class KomentarController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'isi' => 'required'
        ]);

        $komentar = Komentar::create([
          'isi' => $request["isi"]
          // "postingan_id" => Postingan::user()->id
        ]);

        return redirect('/postingan');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($pertanyaan_id)
    {
      //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

app/Http/Controllers/PostinganController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use DB;
use App\Postingan;
use App\Komentar;
use Auth;

class PostinganController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function __construct(){
     $this->middleware('auth')->only(['create', 'store', 'edit', 'update', 'destroy']);
    }

    public function index()
    {
      $komentar = Komentar::all();
      $postingan = Postingan::all();
      return view('postingan.index', compact('postingan', 'komentar'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('postingan.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
      $request->validate([
          'isi' => 'required'
      ]);

      $postingan = Postingan::create([
        'isi' => $request["isi"],
        "user_id" => Auth::user()->id
      ]);

      return redirect('/postingan');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
      //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($postingan_id)
    {
      Postingan::destroy($postingan_id);
      return redirect('/postingan')->with('success', 'Berhasil dihapus!');
    }
}

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Dashboard</div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif

                    You are logged in!
                    <br>
                    <a class="btn btn-primary m-3" href="{{route('postingan.index')}}">Beranda</a>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/layouts/app.blade.php
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-expand-md navbar-light bg-white shadow-sm">
            <div class="container">
                <a class="navbar-brand" href="{{ url('/') }}">
                    {{ config('app.name', 'Laravel') }}
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->
                    <ul class="navbar-nav mr-auto">

                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ml-auto">
                        <!-- Authentication Links -->
                        @guest
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                            </li>
                            @if (Route::has('register'))
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                                </li>
                            @endif
                        @else
                            <li class="nav-item dropdown">
                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                    {{ Auth::user()->name }} <span class="caret"></span>
                                </a>

                                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        {{ __('Logout') }}
                                    </a>

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                        @csrf
                                    </form>
                                </div>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>

        <main class="py-4">
            @yield('content')
        </main>
    </div>
</body>
</html>

resources/views/master.blade.php
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>Sanbercode | SocialMedia </title>
  <!-- Tell the browser to be responsive to screen width -->
  <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- Font Awesome -->
    <link rel="stylesheet" href="{{asset("/plugins/fontawesome-free/css/all.min.css")}}">
    <!-- Ionicons -->
    <link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
    <!-- overlayScrollbars -->
    <link rel="stylesheet" href="{{asset("/dist/css/adminlte.min.css")}}">
    <link rel="stylesheet" href="{{asset("/plugins/datatables-bs4/css/dataTables.bootstrap4.css")}}">
    <!-- Google Font: Source Sans Pro -->
    <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700" rel="stylesheet">
</head>
<body class="hold-transition sidebar-mini">
<!-- Site wrapper -->
  <div class="wrapper">
    <!-- Navbar -->
    <nav class="main-header navbar navbar-expand navbar-white navbar-light">
      <!-- Left navbar links -->
      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>
        </li>
        <li class="nav-item d-none d-sm-inline-block">
          <a href="../../index3.html" class="nav-link">Home</a>
        </li>
        <li class="nav-item d-none d-sm-inline-block">
          <a href="#" class="nav-link">Contact</a>
        </li>
      </ul>

      <!-- SEARCH FORM -->
      <form class="form-inline ml-3">
        <div class="input-group input-group-sm">
          <input class="form-control form-control-navbar" type="search" placeholder="Search" aria-label="Search">
          <div class="input-group-append">
            <button class="btn btn-navbar" type="submit">
              <i class="fas fa-search"></i>
            </button>
          </div>
        </div>
      </form>
      <ul class="navbar-nav ml-auto">
          <!-- Authentication Links -->
          @guest
              <li class="nav-item">
                  <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
              </li>
              @if (Route::has('register'))
                  <li class="nav-item">
                      <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                  </li>
              @endif
          @else
              <li class="nav-item dropdown">
                  <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                      {{ Auth::user()->name }} <span class="caret"></span>
                  </a>

                  <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                      <a class="dropdown-item" href="{{ route('logout') }}"
                         onclick="event.preventDefault();
                                       document.getElementById('logout-form').submit();">
                          {{ __('Logout') }}
                      </a>

                      <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                          @csrf
                      </form>
                  </div>
              </li>
          @endguest
      </ul>
    </nav>
    <!-- /.navbar -->

    <!-- Main Sidebar Container -->
    <aside class="main-sidebar sidebar-dark-primary elevation-4">
      <!-- Brand Logo -->
      <a href="../../index3.html" class="brand-link">
        <img src="../../dist/img/AdminLTELogo.png"
             alt="AdminLTE Logo"
             class="brand-image img-circle elevation-3"
             style="opacity: .8">
        <span class="brand-text font-weight-light">Social Media</span>
      </a>

      <!-- Sidebar -->
      <div class="sidebar">
        <!-- Sidebar user (optional) -->
        <div class="user-panel mt-3 pb-3 mb-3 d-flex">
          <div class="image">
            <img src="{{asset("/dist/img/user2-160x160.jpg")}}" class="img-circle elevation-2" alt="User Image">
          </div>
          <div class="info">
            <a href="#" class="d-block">{{Auth::user()->name}}</a>
          </div>
        </div>
      </div>
      <!-- /.sidebar -->
    </aside>
    <!-- Content Wrapper. Contains page content -->
    <div class="content-wrapper">
      @yield('content')
    </div>
    <!-- /.content-wrapper -->


    <!-- Control Sidebar -->
    <aside class="control-sidebar control-sidebar-dark">
      <!-- Control sidebar content goes here -->
    </aside>
    <!-- /.control-sidebar -->
  </div>
  <!-- ./wrapper -->

  <!-- jQuery -->
  <script src="{{asset("/plugins/jquery/jquery.min.js")}}"></script>
  <!-- Bootstrap 4 -->
  <script src="{{asset("/plugins/bootstrap/js/bootstrap.bundle.min.js")}}"></script>
  <!-- AdminLTE App -->
  <script src="{{asset("/dist/js/adminlte.min.js")}}"></script>
  <!-- AdminLTE for demo purposes -->
  <script src="{{asset("/dist/js/demo.js")}}"></script>
  @stack('scripts')
</body>
</html>

resources/views/postingan/create.blade.php
@extends('master')

@section('content')
<div class="m-3">
  <div class="card card-info">
    <div class="card-header">
      <h3 class="card-title">Buat Pertanyaan</h3>
    </div>
    <!-- /.card-header -->
    <!-- form start -->
    <form method="POST" action="{{route('postingan.store')}}">
    @csrf
      <div class="card-body">
        <!-- <div class="form-group">
          <label for="judul">Judul</label>
          <input type="text" class="form-control" id="judul" name="judul" placeholder="Masukkan Judul">
          @error('judul')
            <div class="alert alert-danger">Form Judul harus diisi</div>
          @enderror
        </div> -->
        <div class="form-group">
          <label for="isi">Isi</label>
          <input type="text" class="form-control" id="isi" name="isi" placeholder="Masukkan Isi">
          @error('isi')
            <div class="alert alert-danger">Form Isi harus diisi</div>
          @enderror
        </div>
      </div>
      <!-- /.card-body -->
      <div class="card-footer">
        <button type="submit" class="btn btn-info">Buat</button>
      </div>
    </form>
  </div>
</div>

@endsection

resources/views/postingan/index.blade.php
@extends('master')

@section('content')
  <div class="m-3">
    <div class="card">
      <!-- /.card-header -->
      <div class="card-body">
        <a class="btn btn-info mb-1" href="{{route('postingan.create')}}">Buat Postingan</a>
      </div>
      <!-- /.card-body -->
    </div>
  </div>

  @forelse($postingan as $key => $postingan)
  <div class="card card-widget ml-3 mr-3 mb-3">
    <div class="card-header">
      <div class="user-block">
        <img class="img-circle" src="{{asset('dist/img/user1-128x128.jpg')}}" alt="User Image">
        <span class="username mt-2"><a href="#">{{$postingan -> author -> name}}</a></span>
      </div>
      <!-- /.user-block -->
      <div class="card-tools">
        <form action="{{route('postingan.destroy', ['postingan' => $postingan->id])}}" method="post">
          @csrf
          @method('DELETE')
          <input type="submit" value="delete" class="btn btn-danger btn-sm">
        </form>
      </div>
      <!-- /.card-tools -->
    </div>
    <!-- /.card-header -->
    <div class="card-body">
    <!-- post text -->
      <p>{{ $postingan -> isi }}</p>
      <!-- Social sharing buttons -->
      <button type="button" class="btn btn-default btn-sm"><i class="far fa-thumbs-up"></i> Like</button>
      <span class="float-right text-muted">45 likes - 2 comments</span>
    </div>
    <div class="card-footer card-comments">
      @forelse($komentar as $key => $komentar)
      <div class="card-comment">
      <!-- User image -->
          <img class="img-circle img-sm" src="../dist/img/user3-128x128.jpg" alt="User Image">

          <div class="comment-text">
            <span class="username">

            </span><!-- /.username -->
            {{$komentar -> isi}}
          </div>
          <hr>
      @empty
          <div class="comment-text">
            <p>Tidak Ada Komentar</p>
          </div>
        <!-- /.comment-text -->
      </div>
      @endforelse
      <!-- /.card-comment -->
    </div>
    <!-- /.card-footer -->
    <div class="card-footer">
      <form action="{{route('komentar.store')}}" method="post">
        @csrf
        <img class="img-fluid img-circle img-sm" src="{{asset('dist/img/user4-128x128.jpg')}}" alt="Alt Text">
        <!-- .img-push is used to add margin to elements next to floating images -->
        <div class="img-push">
          <input type="text" class="form-control form-control-sm" id="isi" name="isi" placeholder="Komentar disini">
          @error('isi')
            <div class="alert alert-danger">Komentar harus diisi</div>
          @enderror
          <button type="submit" class="btn btn-info btn-sm mt-1">Kirim</button>
        </div>
      </form>
    </div>
    <!-- /.card-footer -->
  </div>
  @empty
  <div class="m-3">
    <div class="card">
      <!-- /.card-header -->
      <div class="card-body text-center">
        <p>Tidak Ada Postingan</p>
      </div>
      <!-- /.card-body -->
    </div>
  </div>
  @endforelse
@endsection

resources/views/postingan/show.blade.php
@extends('master')

@section('content')
<div class="card card-widget m-3">
  <div class="card-header">
    <div class="user-block">
      <img class="img-circle" src="{{asset('dist/img/user1-128x128.jpg')}}" alt="User Image">
      <span class="username mt-2"><a href="#">{{$postingan -> author -> name}}</a></span>
    </div>
    <!-- /.user-block -->
    <div class="card-tools">
      <form action="{{route('postingan.destroy', ['postingan' => $postingan->id])}}" method="post">
        @csrf
        @method('DELETE')
        <input type="submit" value="delete" class="btn btn-danger btn-sm">
      </form>
    </div>
    <!-- /.card-tools -->
  </div>
  <!-- /.card-header -->
  <div class="card-body">
  <!-- post text -->
    <p>{{ $postingan -> isi }}</p>
    <!-- Social sharing buttons -->
    <button type="button" class="btn btn-default btn-sm"><i class="far fa-thumbs-up"></i> Like</button>
    <span class="float-right text-muted">45 likes - 2 comments</span>
    <div class="card-footer card-comments mt-2">
      <div class="card-comment">
      <!-- User image -->
        @forelse()
          <img class="img-circle img-sm" src="../dist/img/user3-128x128.jpg" alt="User Image">

          <div class="comment-text">
            <span class="username">
              Maria Gonzales
            </span><!-- /.username -->
            Tes Komentar
          </div>
        <!-- /.comment-text -->
      </div>
      <!-- /.card-comment -->
    </div>
    <!-- /.card-footer -->
    <div class="card-footer">
      <form action="{{route('komentar.store')}}" method="post">
        @csrf
        <img class="img-fluid img-circle img-sm" src="{{asset('dist/img/user4-128x128.jpg')}}" alt="Alt Text">
        <!-- .img-push is used to add margin to elements next to floating images -->
        <div class="img-push">
          <input type="text" class="form-control form-control-sm" id="isi" name="isi" placeholder="Komentar disini">
          @error('isi')
            <div class="alert alert-danger">Komentar harus diisi</div>
          @enderror
          <button type="submit" class="btn btn-info btn-sm mt-1">Kirim</button>
        </div>
      </form>
    </div>
    <!-- /.card-footer -->
  </div>
</div>
@endsection